export const nationalities = [
    { value: "af", label: "Afghan" },
    { value: "al", label: "Albanian" },
    { value: "dz", label: "Algerian" },
    { value: "ar", label: "Argentine" },
    { value: "au", label: "Australian" },
    { value: "at", label: "Austrian" },
    { value: "bh", label: "Bahraini" },
    { value: "bd", label: "Bangladeshi" },
    { value: "be", label: "Belgian" },
    { value: "br", label: "Brazilian" },
    { value: "bg", label: "Bulgarian" },
    { value: "ca", label: "Canadian" },
    { value: "cl", label: "Chilean" },
    { value: "cn", label: "Chinese" },
    { value: "co", label: "Colombian" },
    { value: "hr", label: "Croatian" },
    { value: "cu", label: "Cuban" },
    { value: "cy", label: "Cypriot" },
    { value: "cz", label: "Czech" },
    { value: "dk", label: "Danish" },
    { value: "eg", label: "Egyptian" },
    { value: "ee", label: "Estonian" },
    { value: "fi", label: "Finnish" },
    { value: "fr", label: "French" },
    { value: "de", label: "German" },
    { value: "gr", label: "Greek" },
    { value: "hk", label: "Hong Konger" },
    { value: "hu", label: "Hungarian" },
    { value: "is", label: "Icelandic" },
    { value: "in", label: "Indian" },
    { value: "id", label: "Indonesian" },
    { value: "ir", label: "Iranian" },
    { value: "iq", label: "Iraqi" },
    { value: "ie", label: "Irish" },
    { value: "il", label: "Israeli" },
    { value: "it", label: "Italian" },
    { value: "jp", label: "Japanese" },
    { value: "jo", label: "Jordanian" },
    { value: "kw", label: "Kuwaiti" },
    { value: "lv", label: "Latvian" },
    { value: "lb", label: "Lebanese" },
    { value: "lt", label: "Lithuanian" },
    { value: "lu", label: "Luxembourger" },
    { value: "my", label: "Malaysian" },
    { value: "mt", label: "Maltese" },
    { value: "mx", label: "Mexican" },
    { value: "ma", label: "Moroccan" },
    { value: "nl", label: "Dutch" },
    { value: "nz", label: "New Zealander" },
    { value: "ng", label: "Nigerian" },
    { value: "kp", label: "North Korean" },
    { value: "no", label: "Norwegian" },
    { value: "om", label: "Omani" },
    { value: "pk", label: "Pakistani" },
    { value: "pe", label: "Peruvian" },
    { value: "ph", label: "Philippine" },
    { value: "pl", label: "Polish" },
    { value: "pt", label: "Portuguese" },
    { value: "qa", label: "Qatari" },
    { value: "ro", label: "Romanian" },
    { value: "ru", label: "Russian" },
    { value: "sa", label: "Saudi Arabian" },
    { value: "sg", label: "Singaporean" },
    { value: "za", label: "South African" },
    { value: "kr", label: "South Korean" },
    { value: "es", label: "Spanish" },
    { value: "se", label: "Swedish" },
    { value: "ch", label: "Swiss" },
    { value: "sy", label: "Syrian" },
    { value: "tw", label: "Taiwanese" },
    { value: "th", label: "Thai" },
    { value: "tr", label: "Turkish" },
    { value: "ua", label: "Ukrainian" },
    { value: "ae", label: "Emirati" },
    { value: "gb", label: "British" },
    { value: "us", label: "American" },
    { value: "uy", label: "Uruguayan" },
    { value: "ve", label: "Venezuelan" },
    { value: "vn", label: "Vietnamese" },
  ];

  // Comprehensive list of countries (for passport issue)
  export const countries = [
    { value: "af", label: "Afghanistan" },
    { value: "al", label: "Albania" },
    { value: "dz", label: "Algeria" },
    { value: "ar", label: "Argentina" },
    { value: "au", label: "Australia" },
    { value: "at", label: "Austria" },
    { value: "bh", label: "Bahrain" },
    { value: "bd", label: "Bangladesh" },
    { value: "be", label: "Belgium" },
    { value: "br", label: "Brazil" },
    { value: "bg", label: "Bulgaria" },
    { value: "ca", label: "Canada" },
    { value: "cl", label: "Chile" },
    { value: "cn", label: "China" },
    { value: "co", label: "Colombia" },
    { value: "hr", label: "Croatia" },
    { value: "cu", label: "Cuba" },
    { value: "cy", label: "Cyprus" },
    { value: "cz", label: "Czech Republic" },
    { value: "dk", label: "Denmark" },
    { value: "eg", label: "Egypt" },
    { value: "ee", label: "Estonia" },
    { value: "fi", label: "Finland" },
    { value: "fr", label: "France" },
    { value: "de", label: "Germany" },
    { value: "gr", label: "Greece" },
    { value: "hk", label: "Hong Kong" },
    { value: "hu", label: "Hungary" },
    { value: "is", label: "Iceland" },
    { value: "in", label: "India" },
    { value: "id", label: "Indonesia" },
    { value: "ir", label: "Iran" },
    { value: "iq", label: "Iraq" },
    { value: "ie", label: "Ireland" },
    { value: "il", label: "Israel" },
    { value: "it", label: "Italy" },
    { value: "jp", label: "Japan" },
    { value: "jo", label: "Jordan" },
    { value: "kw", label: "Kuwait" },
    { value: "lv", label: "Latvia" },
    { value: "lb", label: "Lebanon" },
    { value: "lt", label: "Lithuania" },
    { value: "lu", label: "Luxembourg" },
    { value: "my", label: "Malaysia" },
    { value: "mt", label: "Malta" },
    { value: "mx", label: "Mexico" },
    { value: "ma", label: "Morocco" },
    { value: "nl", label: "Netherlands" },
    { value: "nz", label: "New Zealand" },
    { value: "ng", label: "Nigeria" },
    { value: "kp", label: "North Korea" },
    { value: "no", label: "Norway" },
    { value: "om", label: "Oman" },
    { value: "pk", label: "Pakistan" },
    { value: "pe", label: "Peru" },
    { value: "ph", label: "Philippines" },
    { value: "pl", label: "Poland" },
    { value: "pt", label: "Portugal" },
    { value: "qa", label: "Qatar" },
    { value: "ro", label: "Romania" },
    { value: "ru", label: "Russia" },
    { value: "sa", label: "Saudi Arabia" },
    { value: "sg", label: "Singapore" },
    { value: "za", label: "South Africa" },
    { value: "kr", label: "South Korea" },
    { value: "es", label: "Spain" },
    { value: "se", label: "Sweden" },
    { value: "ch", label: "Switzerland" },
    { value: "sy", label: "Syria" },
    { value: "tw", label: "Taiwan" },
    { value: "th", label: "Thailand" },
    { value: "tr", label: "Turkey" },
    { value: "ua", label: "Ukraine" },
    { value: "ae", label: "United Arab Emirates" },
    { value: "gb", label: "United Kingdom" },
    { value: "us", label: "United States" },
    { value: "uy", label: "Uruguay" },
    { value: "ve", label: "Venezuela" },
    { value: "vn", label: "Vietnam" },
  ];